---
- name: install httpd packages
  package: 
     name: "{{ item }}"
     state: present
  with_items:
     - httpd
- name: copy php project
  copy: src=pdo dest=/var/www/html
- name: copy the html file
  copy: src=index.html dest=/var/www/html
- name: copy the configure files
  copy: src=httpd.conf dest=/etc/httpd/conf/

  notify: start appache


